export let wordlist = [
    { word: 'error', description: 'brief description and actions' },
    { word: 'CyberGhost', description: 'brief description and actions' },
    { word: 'Artmoney', description: 'brief description and actions' },
    { word: 'MSI Afterburner', description: 'brief description and actions' },
    { word: 'Kaspersky', description: 'brief description and actions' },
    {
        word: 'One System Care Public',
        description: 'brief description and actions',
    },
    { word: 'Dropbox', description: 'brief description and actions' },
    { word: 'ALTVPN.com', description: 'brief description and actions' },
    { word: 'Cheat Engine', description: 'brief description and actions' },
    {
        word: 'RivaTuner Statistics',
        description: 'brief description and actions',
    },
    { word: 'Avast', description: 'brief description and actions' },
    {
        word: 'Zaxar Games Browser',
        description: 'brief description and actions',
    },
    { word: 'TeamSpeak', description: 'brief description and actions' },
    {
        word: 'SoftEther VPN Client',
        description: 'brief description and actions',
    },
    { word: 'AnTiNooB MoDPack', description: 'brief description and actions' },
    { word: 'Razer', description: 'brief description and actions' },
    {
        word: '360 Total Security',
        description: 'brief description and actions',
    },
    { word: 'granena.ru', description: 'brief description and actions' },
    { word: 'Akamai', description: 'brief description and actions' },
    { word: 'uBar', description: 'brief description and actions' },
    { word: 'ViakaraokeSrv.exe', description: 'brief description and actions' },
    { word: 'RAGE Multiplayer', description: 'brief description and actions' },
    {
        word: 'ASRock eXtreme Tuner',
        description: 'brief description and actions',
    },
    { word: 'ESET', description: 'brief description and actions' },
    { word: 'Sidebar373', description: 'brief description and actions' },
    { word: 'Cacaoweb', description: 'brief description and actions' },
    { word: 'Hideman', description: 'brief description and actions' },
    { word: 'ModManager', description: 'brief description and actions' },
    { word: 'Overwolf', description: 'brief description and actions' },
    { word: 'Avira', description: 'brief description and actions' },
    { word: 'PremierOpinion', description: 'brief description and actions' },
    { word: 'Bitorrent', description: 'brief description and actions' },
    { word: 'µtorrent', description: 'brief description and actions' },
    { word: 'OpenVPN', description: 'brief description and actions' },
    { word: 'Scripthook', description: 'brief description and actions' },
    { word: 'PlayClaw 5', description: 'brief description and actions' },
    { word: 'Bitdefender', description: 'brief description and actions' },
    { word: 'RelevantKnowledge', description: 'brief description and actions' },
    { word: 'Logitech', description: 'brief description and actions' },
    { word: 'LGHub', description: 'brief description and actions' },
    { word: 'LogMeIn', description: 'brief description and actions' },
    { word: 'Hamachi', description: 'brief description and actions' },
    { word: 'GameModding.net', description: 'brief description and actions' },
    { word: 'NAHIMIC', description: 'brief description and actions' },
    { word: 'Norton', description: 'brief description and actions' },
    { word: 'Tok-Cirrhatus', description: 'brief description and actions' },
    { word: 'OneDrive', description: 'brief description and actions' },
    { word: 'VPNium', description: 'brief description and actions' },
    { word: 'Vmods', description: 'brief description and actions' },
    { word: 'Turbo V EVOr', description: 'brief description and actions' },
    { word: 'Malwarebytes', description: 'brief description and actions' },
    { word: 'MailRuUpdater', description: 'brief description and actions' },
    { word: 'Radeon RAMDisk', description: 'brief description and actions' },
    { word: 'Hotspot Shield', description: 'brief description and actions' },
    { word: 'CheMaxRus', description: 'brief description and actions' },
    { word: 'AMD Overdrive', description: 'brief description and actions' },
    {
        word: 'McAfee Security Scan Plus',
        description: 'brief description and actions',
    },
    { word: 'PriceFountain', description: 'brief description and actions' },
    { word: 'KMSPico', description: 'brief description and actions' },
    { word: 'VPNGame', description: 'brief description and actions' },
    { word: 'Cheats 4 Hire', description: 'brief description and actions' },
    { word: 'CPUZ', description: 'brief description and actions' },
    { word: 'GPUZ', description: 'brief description and actions' },
    { word: 'AVG - Lavasoft', description: 'brief description and actions' },
    { word: 'SafeIP', description: 'brief description and actions' },
    { word: 'SafeIPs64.dll', description: 'brief description and actions' },
    { word: 'gtavicecity.ru', description: 'brief description and actions' },
    { word: 'CPU-Tweaker', description: 'brief description and actions' },
    { word: 'Web Companion', description: 'brief description and actions' },
    { word: 'Hideguard', description: 'brief description and actions' },
    { word: 'Nexus Mod Manager', description: 'brief description and actions' },
    { word: 'SetFSB', description: 'brief description and actions' },
    { word: 'proXPN', description: 'brief description and actions' },
    { word: 'RADMIR LAUNCHER', description: 'brief description and actions' },
    { word: 'ATI Tray Tools', description: 'brief description and actions' },
    { word: 'WTFast', description: 'brief description and actions' },
    {
        word: 'LSPD First Response',
        description: 'brief description and actions',
    },
    { word: 'Intel GMA Booster', description: 'brief description and actions' },
    { word: 'Hamachi', description: 'brief description and actions' },
    { word: 'Rage plugin Hook', description: 'brief description and actions' },
    { word: 'Punto Switcher', description: 'brief description and actions' },
    { word: 'Anyconnect YSU', description: 'brief description and actions' },
    { word: 'Script hook', description: 'brief description and actions' },
    {
        word: 'AdGuardianPlus.exe',
        description: 'brief description and actions',
    },
    { word: 'Virnet', description: 'brief description and actions' },
    { word: 'Nexus Mods', description: 'brief description and actions' },
    { word: 'Sonic studio 3', description: 'brief description and actions' },
    { word: 'TunnelBear', description: 'brief description and actions' },
    {
        word: 'Extreme Injector V3',
        description: 'brief description and actions',
    },
    { word: 'Elite Keylogger', description: 'brief description and actions' },
    { word: 'ZenMate', description: 'brief description and actions' },
    { word: 'FiveM', description: 'brief description and actions' },
    { word: 'OpenIV', description: 'brief description and actions' },
    { word: 'Windscribe', description: 'brief description and actions' },
    { word: 'GTA:Multiplayer', description: 'brief description and actions' },
    { word: 'Killer Networking', description: 'brief description and actions' },
    { word: 'WeMod', description: 'brief description and actions' },
    {
        word: 'Killer Network Manager',
        description: 'brief description and actions',
    },
    { word: 'Black Tree Gaming', description: 'brief description and actions' },
    { word: 'Nexus Mod Manager', description: 'brief description and actions' },
    { word: 'OkayFreedom', description: 'brief description and actions' },
    { word: 'Simple Trainer', description: 'brief description and actions' },
    { word: 'GTA trainer', description: 'brief description and actions' },
    { word: 'EnableMPcars', description: 'brief description and actions' },
    {
        word: 'NoBoundaryLimits.asi',
        description: 'brief description and actions',
    },
    { word: 'Toxic_2.1_Free', description: 'brief description and actions' },
    { word: 'Menyoo', description: 'brief description and actions' },
    { word: 'gamerminer', description: 'brief description and actions' },
    { word: 'by.xatab', description: 'brief description and actions' },
    { word: 'Razer Cortex', description: 'brief description and actions' },
    { word: 'reshade', description: 'brief description and actions' },
    { word: 'Corsair Injector', description: 'brief description and actions' },
    { word: '7Launcher GTA 5', description: 'brief description and actions' },
    { word: 'LinGon Mod', description: 'brief description and actions' },
    { word: 'MVDHelper Era', description: 'brief description and actions' },
    { word: 'Ozark.exe', description: 'brief description and actions' },
    { word: 'Mod Menu', description: 'brief description and actions' },
]

export let words = [
    'error',
    'CyberGhost',
    'Artmoney',
    'MSI Afterburner',
    'Kaspersky',
    'One System Care Public',
    'Dropbox',
    'ALTVPN.com',
    'Cheat Engine',
    'RivaTuner Statistics',
    'Avast',
    'Zaxar Games Browser',
    'TeamSpeak',
    'SoftEther VPN Client',
    'AnTiNooB MoDPack',
    'Razer',
    '360 Total Security',
    'granena.ru',
    'Akamai',
    'uBar',
    'ViakaraokeSrv.exe',
    'RAGE Multiplayer',
    'ASRock eXtreme Tuner',
    'ESET',
    'Sidebar373',
    'Cacaoweb',
    'Hideman',
    'ModManager',
    'Overwolf',
    'Avira',
    'PremierOpinion',
    'Bitorrent',
    'µtorrent',
    'OpenVPN',
    'Scripthook',
    'PlayClaw 5',
    'Bitdefender',
    'RelevantKnowledge',
    'Logitech',
    'LGHub',
    'LogMeIn',
    'Hamachi',
    'GameModding.net',
    'NAHIMIC',
    'Norton',
    'Tok-Cirrhatus',
    'OneDrive',
    'VPNium',
    'Vmods',
    'Turbo V EVOr',
    'Malwarebytes',
    'MailRuUpdater',
    'Radeon RAMDisk',
    'Hotspot Shield',
    'CheMaxRus',
    'AMD Overdrive',
    'McAfee Security Scan Plus',
    'PriceFountain',
    'KMSPico',
    'VPNGame',
    'Cheats 4 Hire',
    'CPUZ',
    'GPUZ',
    'AVG - Lavasoft',
    'SafeIP',
    'SafeIPs64.dll',
    'gtavicecity.ru',
    'CPU-Tweaker',
    'Web Companion',
    'Hideguard',
    'Nexus Mod Manager',
    'SetFSB',
    'proXPN',
    'RADMIR LAUNCHER',
    'ATI Tray Tools',
    'WTFast',
    'LSPD First Response',
    'Intel GMA Booster',
    'Hamachi',
    'Rage plugin Hook',
    'Punto Switcher',
    'Anyconnect YSU',
    'Script hook',
    'AdGuardianPlus.exe',
    'Virnet',
    'Nexus Mods',
    'Sonic studio 3',
    'TunnelBear',
    'Extreme Injector V3',
    'Elite Keylogger',
    'ZenMate',
    'FiveM',
    'OpenIV',
    'Windscribe',
    'GTA:Multiplayer',
    'Killer Networking',
    'WeMod',
    'Killer Network Manager',
    'Black Tree Gaming',
    'Nexus Mod Manager',
    'OkayFreedom',
    'Simple Trainer',
    'GTA trainer',
    'EnableMPcars',
    'NoBoundaryLimits.asi',
    'Toxic_2.1_Free',
    'Menyoo',
    'gamerminer',
    'by.xatab',
    'Razer Cortex',
    'reshade',
    'Corsair Injector',
    '7Launcher GTA 5',
    'LinGon Mod',
    'MVDHelper Era',
    'Ozark.exe',
    'Mod Menu',
]
