export let words = [
    'CyberGhost',
    'Artmoney',
    'MSI Afterburner',
    'Kaspersky',
    'One System Care Public',
    'Dropbox',
    'ALTVPN.com',
    'Cheat Engine',
    'RivaTuner Statistics',
    'Avast',
    'Zaxar Games Browser',
    'TeamSpeak',
    'SoftEther VPN Client',
    'AnTiNooB MoDPack',
    'Razer',
    '360 Total Security',
    'granena.ru',
    'Akamai',
    'uBar',
    'ViakaraokeSrv.exe',
    'RAGE Multiplayer',
    'ASRock eXtreme Tuner',
    'ESET',
    'Sidebar373',
    'Cacaoweb',
    'Hideman',
    'ModManager',
    'Overwolf',
    'Avira',
    'PremierOpinion',
    'Bitorrent',
    'µtorrent',
    'OpenVPN',
    'Scripthook',
    'PlayClaw 5',
    'Bitdefender',
    'RelevantKnowledge',
    'Logitech',
    'LGHub',
    'LogMeIn',
    'Hamachi',
    'GameModding.net',
    'NAHIMIC',
    'Norton',
    'Tok-Cirrhatus',
    'OneDrive',
    'VPNium',
    'Vmods',
    'Turbo V EVOr',
    'Malwarebytes',
    'MailRuUpdater',
    'Radeon RAMDisk',
    'Hotspot Shield',
    'CheMaxRus',
    'AMD Overdrive',
    'McAfee Security Scan Plus',
    'PriceFountain',
    'KMSPico',
    'VPNGame',
    'Cheats 4 Hire',
    'CPUZ',
    'GPUZ',
    'AVG - Lavasoft',
    'SafeIP',
    'SafeIPs64.dll',
    'gtavicecity.ru',
    'CPU-Tweaker',
    'Web Companion',
    'Hideguard',
    'Nexus Mod Manager',
    'SetFSB',
    'proXPN',
    'RADMIR LAUNCHER',
    'ATI Tray Tools',
    'WTFast',
    'LSPD First Response',
    'Intel GMA Booster',
    'Hamachi',
    'Rage plugin Hook',
    'Punto Switcher',
    'Anyconnect YSU',
    'Script hook',
    'AdGuardianPlus.exe',
    'Virnet',
    'Nexus Mods',
    'Sonic studio 3',
    'TunnelBear',
    'Extreme Injector V3',
    'Elite Keylogger',
    'ZenMate',
    'FiveM',
    'OpenIV',
    'Windscribe',
    'GTA:Multiplayer',
    'Killer Networking',
    'WeMod',
    'Killer Network Manager',
    'Black Tree Gaming',
    'Nexus Mod Manager',
    'OkayFreedom',
    'Simple Trainer',
    'GTA trainer',
    'EnableMPcars',
    'NoBoundaryLimits.asi',
    'Toxic_2.1_Free',
    'Menyoo',
    'gamerminer',
    'by.xatab',
    'Razer Cortex',
    'reshade',
    'Corsair Injector',
    '7Launcher GTA 5',
    'LinGon Mod',
    'MVDHelper Era',
    'Ozark.exe',
    'Mod Menu',
]
